export const FETCH_LEAD_DETAIL = 'FETCH_LEAD_DETAIL';
export const SAVE_LEAD_DETAIL = 'SAVE_LEAD_DETAIL';
export const SHOW_MODAL = 'SHOW_MODAL';
export const SHOW_MODAL_SPINNER = 'SHOW_MODAL_SPINNER';
export const HIDE_MODAL_SPINNER = 'HIDE_MODAL_SPINNER';
export const HIDE_MODAL = 'HIDE_MODAL';
export const ADD_LEAD = 'ADD_LEAD';
export const EDIT_LEAD = 'EDIT_LEAD';