export const ON_PHONE_CHANGE = 'ON_PHONE_CHANGE';
export const ON_FIO_CHANGE = 'ON_FIO_CHANGE';
export const ON_DATE_CHANGE = 'ON_DATE_CHANGE';
export const ON_SOURCE_CHANGE = 'ON_SOURCE_CHANGE';
export const ON_STATUS_CHANGE = 'ON_STATUS_CHANGE';
export const ON_RESPONSIBLE_CHANGE = 'ON_RESPONSIVE_CHANGE';
export const ON_SUPERVISOR_CHANGE = 'ON_SUPERVISOR_CHANGE';
export const RESET_FILTER = 'RESET_FILTER';

